[package]
name = "pinfish-macros"
version = "0.1.0-alpha"
edition = "2021"
license = "MIT"
description = "proc macros for pinfish"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
